name: "2021"

on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/2021.yml
      - '2021/**'
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/2021.yml
      - '2021/**'
  workflow_dispatch:

jobs:
  test-results:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./2021

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: bash scripts/build.sh

      - name: Test
        run: bash scripts/test.sh

  test-ASAN:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./2021
    env:
      BUILD_TYPE: RelWithDebInfo
      ADRESS_SANITIZER: 1

    steps:
      - uses: actions/checkout@v2
      
      - name: Build
        run: bash scripts/build.sh

      - name: Test
        run: bash scripts/test_all.sh

  test-TSAN:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./2021
    env:
      BUILD_TYPE: RelWithDebInfo
      THREAD_SANITIZER: 1

    steps:
      - uses: actions/checkout@v2
      
      - name: Build
        run: bash scripts/build.sh

      - name: Test
        run: bash scripts/test_all.sh
