name: "2022"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/2022.yml
      - "2022/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      AOC_2022_ROOT: ${{ github.workspace }}/2022
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: "1.18"
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: ${{ github.workspace }}/2022
          args: --config=.golangci-ci.yaml
      - name: Test
        working-directory: ${{ github.workspace }}/2022
        run: |
          go test ./...--race
      - name: Coverage
        working-directory: ${{ github.workspace }}/2022
        run: |
          # Prints coverage info just for informational purposes
          ./coverage.sh

  solve-and-time:
    runs-on: ubuntu-latest
    env:
      AOC_2022_ROOT: ${{ github.workspace }}/2022
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: "1.18"
      - name: Build and Run
        working-directory: ${{ github.workspace }}/2022
        run: |
          ./run_all.sh
