name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: bash scripts/build.sh

      - name: Test
        run: bash scripts/test.sh

  test-fsanitize:
    runs-on: ubuntu-latest
    env:
      BUILD_TYPE: RelWithDebInfo
      ADRESS_SANITIZER: 1

    steps:
      - uses: actions/checkout@v2
      
      - name: Build
        run: bash scripts/build.sh

      - name: Test
        run: bash scripts/test_sanitizer.sh
