name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: bash build.sh

      - name: Test
        run: bash test.sh

  Valgrind-check:
    runs-on: ubuntu-latest
    env:
      BUILD_TYPE: Debug

    steps:
      - uses: actions/checkout@v2

      - name: Install valgrind
        run: |
             sudo apt update
             sudo apt install -y valgrind
      
      - name: Build
        run: bash build.sh

      - name: Test
        run: bash test_valgrind.sh
