name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: bash build.sh

      - name: Test
        run: bash test.sh

  Sanitizer tests:
    runs-on: ubuntu-latest
    env:
      BUILD_TYPE: Debug
      ADRESS_SANITIZER: 1

    steps:
      - uses: actions/checkout@v2
      
      - name: Build
        run: bash build.sh

      - name: Test
        run: bash test_sanitizer.sh
