name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: bash build.sh

      - name: Test
        run: bash test.sh

  build_and_test_valgrind:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install valgrind
        run: |
             sudo apt update
             sudo apt install -y valgrind
      
      - name: Build
        run: bash build.sh Debug

      - name: Test
        run: bash test_valgrind.sh
